#!/bin/bash

./fabber --method=spatialvb --noise=white --allow-bad-voxels --param-spatial-priors=MN --output=../Fabber_Results/ --data1=../Fabber_Results/brain_4_n_24h.nii.gz --model=BOLD2c --mask=../Fabber_Results/brain_4l_mask.nii.gz --TE=0.074 --tau1=-0.016 --tau2=-0.008 --tau3=0.0 --tau4=0.008 --tau5=0.016 --tau6=0.024 --tau7=0.032 --tau8=0.040 --tau9=0.048 --tau10=0.056 --tau11=0.064
