#!/bin/bash

./fabber_qbold --method=vb --noise=white --max-iterations=10 \
    --save-residuals --save-model-fit \
    --output=../../Data/Fabber_Results/ \
    --data1=../../Data/subject_02_ASE_norm.nii.gz \
    --model=qboldR2p \
    --mask=../../Data/subject_02_mask.nii.gz \
    --TE=0.074 \
    --tau1=-0.028 --tau2=-0.024 --tau3=0.020 --tau4=-0.016 --tau5=-0.012 --tau6=-0.008 \
    --tau7=-0.004 --tau8=0.0 --tau9=0.004 --tau10=0.008 --tau11=0.012 --tau12=0.016 \
    --tau13=0.02 --tau14=0.024 --tau15=0.028 --tau16=0.032 --tau17=0.036 --tau18=0.04 \
    --tau19=0.044 --tau20=0.048 --tau21=0.052 --tau22=0.056 --tau23=0.06 --tau24=0.064
