function L = MTC_loglike(data,model,sigma)
% Calculate log likelihood. Usage:
%
%       L = MTC_loglike(data,model,sigma)
%
% Takes inputs of raw DATA (1xN vector), values generated by the MODEL
% (also 1xN vector), and a noise standard deviation SIGMA (scalar). Returns
% a scalar log likelihood value L.
%
%
%       Copyright (C) University of Oxford, 2018
%
%
% Created by MT Cherukara, 12 January 2018
%
% CHANGELOG:
    
% make sure inputs are correct
if (length(data) ~= length(model))
    error('Input Data and Model Data must be the same length!');
end

% extract N
N = length(data);

% compute maximum possible loglikelihood
M = -0.5.*N.*log(2.*pi.*sigma.^2);

% compute sum of square difference
S = (1./(2.*sigma.^2)).*sum((data-model).^2);

% add up loglikelihood
L = M - S;