% MTC_simAnalyse.m
% 
% Analysis of vessel simulation data generated by simrun.m (which calls the
% function simplevesselsim.m). This script should be a GUI-based anaylis
% tool, allowing the user to select a saved .mat file (which should contain
% 1 or 2 stored phase matrices, and a p structure containing all parameter
% information, and maybe some other stuff).
%
% The actual calculations of the anaylsis will generally be performed by
% the function MTC_plotSignal, which will be called in this script, and
% given specific functional specifiers by it (although MTC_plotSignal
% should still be useable on its own, as in within simrun.m)
%
% 
%       Copyright (C) University of Oxford, 2017
%
% 
% Created by MT Cherukara, February 2017
%
% THIS IS AN OLD VERSION - simAnalyse.m has replaced this, as of Feb 2017


close all; clear;

% optional arguments
includeT2 = 1;  % include T2 elements
NormMean  = 0;  % normalise plots

%% Load data
[dataname,datadir] = uigetfile('*.mat','Select Vessel Simulation Dataset...');
load(strcat(datadir,dataname));

%% Calculate without T2
% calculate the mean and standard deviation of both
meanu = mean(sASE_u,2);
meann = mean(sASE_n,2);
stdu = std(sASE_u,[],2);
stdn = std(sASE_n,[],2);

% normalise
if NormMean
    meann = meann./meanu;   % means - normal-dist first
    meanu = meanu./meanu;   
    stdu = stdu./meanu;     % standard deviations
    stdn = stdn./meanu;
end

% variables for plotting things
xls = 1000*p.TE + 2;

%% plot data without T2 effects
% figure(11)
% errorbar(1000*tASE,meanu,stdu,':','LineWidth',1.5); hold on;
% errorbar(1000*tASE+1,meann,stdn,'-','LineWidth',1.5); % add an offset, so we can see them better
% legend('Permeable Walls','Solid Walls','Location','South');
% ylabel('Signal Normalised to Uniform Distribution');
% xlabel('Spin Echo offset \tau (ms)');
% set(gca,'FontSize',16);
% title(['DBV = ',num2str(p.vesselFraction),...
%      ', R = ',num2str(p.R*1e6),'\mum',...
%      ', D = ',num2str(p.D),'m^2/s',...
%      ', T_2 = 0']);
%  if NormMean
%      axis([-xls, xls, 0.95, 1.05]);
%  else
%      axis([-xls, xls, 0.5, 1]);
%  end


%% Calculate the same stuff, but with T2
if includeT2
    
    sASE_u  = zeros(round(500*p.TE)+1,length(X));
    sASE_n  = zeros(round(500*p.TE)+1,length(X));
    
    % calculate again
    for j = 1:10
        [sASE_u(:,j), ~   ]  = MTC_plotSignal(p,Phase_u(:,:,j),'sequence','ASE','display',false,'T2EV',0.11);
        [sASE_n(:,j), tASE]  = MTC_plotSignal(p,Phase_n(:,:,j),'sequence','ASE','display',false,'T2EV',0.11);
    end
    
    % calculate the mean and standard deviation of both
    meanu = mean(sASE_u,2); 
    meann = mean(sASE_n,2);
    stdu = std(sASE_u,[],2); 
    stdn = std(sASE_n,[],2);

    % normalise and scale
    if NormMean
        meann = meann./meanu;   % means - normal-dist first
        meanu = meanu./meanu;   
        stdu = stdu./meanu;     % standard deviations
        stdn = stdn./meanu;
    end
    
    % plot
    figure(12)
    errorbar(1000*tASE,meanu,stdu,':','LineWidth',1.5); hold on;
    errorbar(1000*tASE+1,meann,stdn,'-','LineWidth',1.5); % add an offset, so we can see them better
    legend('Permeable Walls','Solid Walls','Location','South');
    ylabel('Signal Normalised to Uniform Distribution');
    xlabel('Spin Echo offset \tau (ms)');
    set(gca,'FontSize',16);
    title(['DBV = ',num2str(p.vesselFraction),...
         ', R = ',num2str(p.R*1e6),'\mum',...
         ', D = ',num2str(p.D),'m^2/s',...
         ', T_2 = 110ms']);
     % set axis
     if NormMean
         axis([-xls, xls, 0.95, 1.05]);
     else
         axis([-xls, xls, 0.3, 0.8]);
     end
     
end