#!/bin/bash

./fabber --method=spatialvb --noise=white --allow-bad-voxels --param-spatial-priors=MM --output=../Fabber_Results/ --data1=../Fabber_Results/brain_3_longT.nii.gz --model=BOLDR2 --mask=../Fabber_Results/brain_3_mask.nii.gz --tau1=0.032 --tau2=0.036 --tau3=0.040 --tau4=0.044 --tau5=0.048 --tau6=0.052 --tau7=0.056 --tau8=0.06 --tau9=0.064
